name: dating_app
description: ""
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.9
  lottie: ^3.1.2

  # state management
  #flutter_riverpod: ^2.4.4
  flutter_bloc: ^8.1.5

  #firebase
  firebase_core: ^3.2.0
  firebase_messaging: ^15.0.3
  firebase_crashlytics: ^4.3.0
  cloud_firestore: ^5.6.1

  #debuging
  logger: ^2.4.0

  # networking
  dio: ^5.5.0+1
  pretty_dio_logger: ^1.3.1
  dio_smart_retry: ^7.0.1
  flutter_html: ^3.0.0-beta.2

  # routing
  auto_route: ^9.2.2

  # dependency injection
  get_it: ^8.0.3

  # json parsing
  json_annotation: ^4.8.1
  iconly: ^1.0.1


  # caching
  shared_preferences: ^2.2.3


  #localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2


  # utils
  flutter_webrtc: ^1.0.0
  uuid: ^4.5.1
  camera: ^0.11.0+2
  image_picker: ^1.1.2
  email_validator: ^3.0.0
  equatable: ^2.0.5
  flutter_screenutil: ^5.9.3
  theme_extensions_builder_annotation: ^3.1.0
  permission_handler: ^11.0.1
  flutter_dotenv: ^5.2.1
  clipboard: ^2.0.2
  share_plus: ^11.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_utils: ^2.8.2
  # code generation
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2
  theme_extensions_builder: ^3.1.0
  auto_route_generator: ^9.0.0
  flutter_launcher_icons: ^0.14.2

  # linter
  very_good_analysis: ^7.0.0

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios : true
  image_path: "assets/icons/gem.png"


flutter_gen:
  output: lib/core/assets/
  integrations:
    flutter_svg: true
    lottie: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/icons/
    - .env

flutter_intl:
  enabled: true


